src/Util/ASTUtil.js

Currently, an error occurs when I target files including jsx syntax like below.
```js
import React from 'react';
class App extends React.Component {
render() {
return <div>Hello</div>;
}
}
```
* error trace
```
Error: Unknown node type JSXElement.
at Controller.traverse (/Users/koba04/project/node_modules/esdoc/node_modules/estraverse/estraverse.js:515:31)
at Object.traverse (/Users/koba04/project/node_modules/esdoc/node_modules/estraverse/estraverse.js:707:27)
at Function.findPathInImportDeclaration (/Users/koba04/project/node_modules/esdoc/out/src/Util/ASTUtil.js:60:31)
at ClassDoc._resolveLongname (/Users/koba04/project/node_modules/esdoc/out/src/Doc/AbstractDoc.js:943:51)
at ClassDoc._extends (/Users/koba04/project/node_modules/esdoc/out/src/Doc/ClassDoc.js:137:29)
at ClassDoc._apply …
```

Support JSXElement. (no parse)

---

doc/src/documents/tags.html.md

`!number` is equivalent to `number`, so I think it is not a good example.
Instead use `!Object`.
> Functions and all value types (boolean, number, and string) are
> non-nullable by default whether or not they are declared with the
> Non-nullable operator. To make a value or function type nullable, use
> the Nullable operator.
> https://developers.google.com/closure/compiler/docs/js-for-compiler#types

Use good example for not nullable types

---

src/Publisher/Builder/DocBuilder.js

String is used as shortcut syntax as we use like `npm install user/repo`.
See https://docs.npmjs.com/files/package.json#repository for more details.
```diff
diff --git a/test/fixture/package.json b/test/fixture/package.json
index c02f8fa..1b42a19 100644
--- a/test/fixture/package.json
+++ b/test/fixture/package.json
@@ -1,9 +1,6 @@
{
"name": "esdoc-test-fixture",
"version": "1.2.3",
-  "repository": {
-    "type": "git",
-    "url": "https://github.com/h13i32maru/esdoc"
-  },
+  "repository": "h13i32maru/esdoc",
"main": "./out/src/MyClass.js"
}
```
```
$ npm run test
> esdoc@0.1.4 test /Users/r7kamura/src/github.com/h13i32maru/esdoc
> node ./script/test.js
error: could not parse /Users/r7kamura/src/github.com/h13i32maru/esdoc/test/fixture/src/UnknownSyntax.js
badge.svg …
```

Fix error on string repository property in package.json

---

src/ESDocCLI.js

Hi! 
I suggest 'requiring' esdoc configuration via nodejs instead of manually parsing like it is done in webpack. This provides opportunity to specify some values in config dinamically, do some processing etc.
For example I have 'includes' and 'excludes' values configured in my build system, and i want these values imported to esdoc config.
This change does not break current json-format configurations as nodejs supports 'requiring' json out of the box as well as commonjs.

allow commonjs as configs

---

src/Doc/VariableDoc.js
test/fixture/src/MyClass.js
test/src/BuilderTest/CoverageDocTest.js

First of all, thanks for this great tool.
This PR fixes the bug #76. I referred to the previous commit 5142a9fbdc3c81939835eac0f48c84027507c2fa when writing this. I've not yet fully understood the source code of esdoc, so please let me know if there is any further line I should modify.
Cheers :smile:

Fix crashing at top-level array destructuring

---

package.json
src/Doc/MethodDoc.js
test/fixture/src/MyClass.js
test/src/BuilderTest/CoverageDocTest.js
test/src/BuilderTest/IdentifiersDocTest.js

Hi,
I've just uploaded the previous PR and I found the issue #73 is somewhat similar to it. However, I cannot be sure if this way is what you would like. Any comment will be welcomed, so that I can modify along with it.
Cheers :+1:

fix: crash when [Symbol.iterator] is declared in a class.

---

src/Parser/ParamParser.js
test/fixture/src/myFunction.js
test/src/BuilderTest/CoverageDocTest.js
test/src/BuilderTest/FunctionDocTest.js
test/src/BuilderTest/NavDocTest.js
test/src/BuilderTest/nAnonymousTest.js
test/src/UnitTest/ParamParserTest.js

When setting a default parameter to an object (e.g. `funcName(argOne = {})`), the `@param` component is parsed incorrectly.
I tracked down the issue to [ParamParser.js](https://github.com/blindman/esdoc/commit/f929cdac3f04524247abe920e46e85f8b82d38a4#diff-e444415be441b7d1fff0b4819049cd75) where the regex used in the `match` function assigning to `match` and the `replace` function assigning to `value` are not the same.  I am not sure if these are purposely different but I changed them to match and added tests to account for the changes made.
Example:

Parsing default params when the default is set to "{}"

---

package.json
src/Plugin/Plugin.js
src/Publisher/publish.js
test/fixture/plugin/MyPlugin1.js
test/src/UnitTest/ESDocPluginTest.js

I am working on a plugin, and would like to modify the html based on the file that is being generated.
I've added a simple test case, and confirmed that the fileName is being passed in the ev.data.
This commit allows me to write plugins that do things like removing the navigation on certain pages, or adding 'active' links in the header based on a regex.
It would be nice to pass this value in *all* plugin events, but I really want it onHandleHTML().
Docs haven't been updated.
Version has been tagged and bumped to 0.4.4.

adding filename to onHandleHTML() plugin event

---

src/Parser/ParamParser.js
test/fixture/empty-type.json
test/fixture/src-error/EmptyType.js
test/src/UnitTest/EmptyTypeTest.js

fixes: #198
If you don't include a type it won't cause an error but if empty types are included like:
```javascript
/**
* @return {string|} has an empty component
* @throws {} this is empty
*/
function f() {
}
```
Throw an error with the name/description of the param with an empty type.

fix: Empty types give useful errors

---

src/Publisher/Builder/DocBuilder.js

Fixes #202.
Just adds a check on `url` before attempting to parse it in case user left `repository.url` empty in `package.json`.

fix #202 empty repository url

---

src/Publisher/Builder/CoverageBuilder.js

Hello :)
Fix coverage percent when file is zero.
Previous
```
==================================
Coverage: NaN% (0/0)
==================================
```
Revised
```
==================================
Coverage: 0% (0/0)
==================================
```

Fix coverage percent when expectCount is zero

---

src/Parser/ESParser.js
src/Plugin/Plugin.js

@h13i32maru Please review this PR as it exposes all data available in ESParser to parsing related plugin callbacks. It is rather handy to have the file path (`filePath`) for instance in `onHandleCode` and `onHandleAST` for the source code being processed. 
Please let me know if any changes need to be made and I'll update the PR. I have a really significant ESDoc plugin for interactive visualization of source code that is blocked without more plugin data for AST processing.

Exposed more variables to ESParser related plugin callbacks.

---

src/ESDocCLI.js

hello:)
I added command options in help.
```
ᐅ esdoc -h
usage: esdoc [-c esdoc.json]
Options:
-c create the documents
-h output usage information
-v output the version number
```
thanks.

Add options in help

---

src/Typedef/typedef.js

Previously the documentation form `[v]` was missing a close-curly (`}`) which caused the rest of the line to be parsed incorrectly.

Correct `v` documentation in typedef.js

---

package.json
src/Doc/AbstractDoc.js
src/Doc/AssignmentDoc.js
src/Doc/ClassDoc.js
src/Doc/ExternalDoc.js
src/Doc/FileDoc.js
src/Doc/FunctionDoc.js
src/Doc/MemberDoc.js
src/Doc/MethodDoc.js
src/Doc/TestDoc.js
src/Doc/TestFileDoc.js
src/Doc/TypedefDoc.js
src/Doc/VariableDoc.js
src/Factory/DocFactory.js
src/Util/ASTUtil.js

- remove internal private tag (aka `@_foo`)
- naming rule for tags to methods
- before: `['@foo'](){}`
- after: `_$foo(){}`

Remove internal tag

---

src/Publisher/Builder/DocBuilder.js

Just as an example, how better error descriptions could be implemented.
Would fix #351 (at least as a workaround). Later referencing filename and lineno would be nice.

Better error message for invalid function type annotation

---

src/Parser/ParamParser.js
test/fixture/package/src/Guess/Return.js
test/src/HTMLTest/CoverageTest/CoverageTest.js

Minimal sample to reproduce crash:
```javascript
function noReturnDocTag() {
const o = {};
return { ...o };
}
```
Esdoc try to guess function return type when not `@return` tag found. When return type is Object, most times it can determine it's shape from AST. But when this object contains rest spread operator, it became compicated (for ex `return { ...obj }`, theorethically we can try track deeper and determine shape of `obj`, but for now we simple break guessing with `*`). In any case, this commit fixed crash with this case, because when AST node contain object with type `SpreadProperty`, it of course has no `key`.

Fix crash with guessing return type

---

src/Parser/CommentParser.js

@ symbols inside code blocks are currently mistakenly interpreted as tags, making it difficult to have code examples for decorators. This PR escapes them, rather naively. Willing to try to do a better fix, but since this code is marked for refactor I figure @h13i32maru has plans for it anyways.

bugfix(comments): Escapes @ symbols in code blocks

---

src/Doc/AbstractDoc.js

Currently esdoc fails for code containing a call expression in 'extends' clauses which is a supported feature and is popular with mixins.
Failing code:
```
function mix() {
return {
with: function () {
return class { };
}
};
}
class Test extends mix().with() { }
```

fix(parser): support parsing expressions in extend clause

---

package-lock.json
package.json

Closes #492, #495, esdoc/esdoc-plugins#50
The local build (`npm test`) is still passing with this change.
**Update**: This PR brings the `marked` dependency to a newer version than #496, but either one will get rid of the security issues.

Updated 'marked' to address the security issues

---

src/ESDoc.js

This PR addresses https://github.com/esdoc/esdoc/issues/432, a bug where esdoc fails to run if a `README.md` file is not present at the root of a given project. The bug occurs because the default behaviour of esdoc is to attempt to read that file regardless of whether or not it exists.
The simple solution here is to check if the file exists before attempting to read from it, and fall back to empty string as the index content if the file does not exist.
On the [issue](https://github.com/esdoc/esdoc/issues/432) there are [reports](https://github.com/esdoc/esdoc/issues/432#issuecomment-322345001) of esdoc also crashing if a readme is present at the top level of the project but its not named exactly `README.md`, which may frequently be the case on case sensitive file systems. This PR does not …

check if README.md exists before attempting to read it

---

src/ESDoc.js
src/Typedef/typedef.js
test/integration-test/esdoc.json
test/integration-test/src/_Misc/outputAST.test.js

Per the request of @h13i32maru 
* `config.outputAST` is true by default
* if `config.outputAST` is true - ast is generated, otherwise skipped
* fixes #406 if user is made aware to set config.outputAST to false.

fixes #406 - allow config to disable ast json generation
